import type { Product } from "@/components/CardProduct";

export const products: Product[] = [
    {
        "id": 1,
        "name": "Vital + comida para perros sabor carne y vegetales 2kg",
        "description": "Alimentos balanceados para perros adultos de todas las razas",
        "price": 100,
        "priceDiscount": 80,
        "stock": 100,
        "tags": ["Mascotas", "Alimentos", "Perros", "Pequeños"],
        "image": "/Vital+.png"
    },
    {
        "id": 2,
        "name": "ZenCat comida para gatos sabor salmon 1.5kg",
        "description": "ZenCat es un alimento balanceado para gatos adultos de todas las razas",
        "price": 100,
        "priceDiscount": 80,
        "stock": 100,
        "tags": ["Mascotas", "Alimentos", "Gatos", "Pequeños"],
        "image": "/ZenCat.png"
    },
    {
        "id": 3,
        "name": "PawFuel Mature Raza Pequeña",
        "description": "PawFuel Mature es un alimento balanceado para perros adultos de todas las razas",
        "price": 100,
        "priceDiscount": 80,
        "stock": 100,
        "tags": ["Mascotas", "Alimentos", "Perros", "Grandes"],
        "image": "/Mature.png"
    },
    {
        "id": 4,
        "name": "PowerBites",
        "description": "PowerBites son unos snacks especiales para el entrenamiento de tus mascotas",
        "price": 100,
        "priceDiscount": 80,
        "stock": 100,
        "tags": ["Mascotas", "Snacks", "Perros", "Gatos", "Pequeños"],
        "image": "/PowerBites.png"
    },
    {
        id: 5,
        name: "DogChow Cachorro Pollo y Arroz 3kg",
        description: "Alimento completo para perros cachorros con pollo y arroz",
        price: 120,
        priceDiscount: 95,
        stock: 80,
        tags: ["Mascotas", "Alimentos", "Perros", "Cachorros"],
        image: "/DogChowCachorro.png",
    },
    {
        id: 6,
        name: "Whiskas Gatitos Carne y Leche 1.2kg",
        description: "Nutrición esencial para gatitos con sabor a carne y leche",
        price: 110,
        priceDiscount: 90,
        stock: 60,
        tags: ["Mascotas", "Alimentos", "Gatos", "Cachorros"],
        image: "/WhiskasGatitos.png",
    },
    {
        id: 7,
        name: "PawFuel Dental Sticks 7 unidades",
        description: "Snacks dentales que ayudan a reducir el sarro en perros pequeños",
        price: 70,
        priceDiscount: 60,
        stock: 150,
        tags: ["Mascotas", "Snacks", "Perros", "Higiene"],
        image: "/DentalSticks.png",
    },
    {
        id: 8,
        name: "ZenCat Senior 2kg",
        description: "Alimento especializado para gatos mayores de 7 años",
        price: 130,
        priceDiscount: 105,
        stock: 50,
        tags: ["Mascotas", "Alimentos", "Gatos", "Senior"],
        image: "/ZenCatSenior.png",
    },
    {
        id: 9,
        name: "CatJoy Arena Sanitaria 5kg",
        description: "Arena absorbente y sin aroma para gatos exigentes",
        price: 60,
        priceDiscount: 55,
        stock: 200,
        tags: ["Mascotas", "Aseo", "Gatos", "Arena"],
        image: "/CatJoyArena.png",
    },
    {
        id: 11,
        name: "SnackyCat Mix 80g",
        description: "Snacks crocantes y sabrosos para gatos adultos",
        price: 40,
        priceDiscount: 35,
        stock: 300,
        tags: ["Mascotas", "Snacks", "Gatos", "Adultos"],
        image: "/SnackyCatMix.png",
    },
    {
        id: 12,
        name: "PawFuel Active Mediana 2.5kg",
        description: "Alimento para perros activos de raza mediana con proteínas reforzadas",
        price: 140,
        priceDiscount: 115,
        stock: 70,
        tags: ["Mascotas", "Alimentos", "Perros", "Medianos"],
        image: "/ActiveMediana.png",
    },
]